### ISSUE TITLE
Can I use your pretrained model in transformers?

### ISSUE THREAD

**Issue by ky941122** [allenai/unifiedqa#1]
Hi, is this possible to use your checkpoints in transformers? If can, how?

**Comment by joe32140** [comment]
#2 please take a look at my example code.

**Comment by posuer** [comment]
> #2 please take a look at my example code.

Thank you! This is very helpful!
Please include the code in README.md. 
It took me days to finally come here and successfully load your checkpoints.

**Comment by posuer** [comment]
> #2 please take a look at my example code.

Thank you! This is very helpful!
It would be great if the owner of this repo includes the code in README.md.

**Comment by danyaljj** [comment]
Sorry just seeing it now :-/
