### ISSUE TITLE
Multi-Paragraph

### ISSUE THREAD

**Issue by jiajudu** [allenai/unifiedqa#10]
How to process documents when their length exceed the maximum number of Bart/T5's input tokens?

**Comment by danyaljj** [comment]
We haven't studied such cases. I suppose you can split your into smaller chunks and solver them separately.

**Comment by chen-yifu** [comment]
Hi, can someone please tell me what is the "maximum number of Bart/T5's input tokens"? Thank you in advance!

**Comment by jiajudu** [comment]
For example, Bart can process 1024 tokens at every turn.
