### ISSUE TITLE
Further Fine-tuning on T5

### ISSUE THREAD

**Issue by chen-yifu** [allenai/unifiedqa#13]
Hi, thank you for viewing this post. 

I'm trying to fine-tune your UnifiedQA-11B and UnifiedQA-3B models on custom QA datasets. My issue is that I'm not sure how to use the script provided by Google's T5 repository:
```
t5_mesh_transformer  \
  --tpu="${TPU_NAME}" \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --model_dir="${MODEL_DIR}" \
  --t5_tfds_data_dir="${DATA_DIR}" \
  --gin_file="dataset.gin" \
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '${TPU_SIZE}'" \
  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
  --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin"
```

Is fine-tuning UnifiedQA T5 any different than fine-tuning the original vanilla T5?
Can someone please let me know if there are example notebooks available for further fine-tuning your UnifiedQA T5 models?

Thanks so much!

**Comment by chen-yifu** [comment]
Update:
I've downloaded the 3B checkpoint from your GCS bucket and uploaded to this colab notebook: https://colab.research.google.com/drive/1_Sm7svPWsngDd9l9jKWqpl1mwLYWX1Bp?usp=sharing

However, it's showing another error as follows:

Can someone please help with debugging this? Thanks again!

![image](https://user-images.githubusercontent.com/45907512/107733644-57eb1480-6cb0-11eb-88ea-bc16cf51c11d.png)

**Comment by danyaljj** [comment]
> Is fine-tuning UnifiedQA T5 any different than fine-tuning the original vanilla T5? 

When fine-tuning on vanilla T5, `${PROJECT}` is set to Google's released checkpoints. However,  when finetuning on UnifiedQA, `${PROJECT}` is set to one of the checkpoints we have released here (see the readme).
