### ISSUE TITLE
score associated with a result?

### ISSUE THREAD

**Issue by SourAlderson** [allenai/unifiedqa#14]
I have a large text on which I want to implement extractive question-answering with UnifiedQA. I am currently running loops  to run the model on smaller batches since there is token size limitation. But how do I rank the results from each batch. Is there any score associated with a result? Kindly help

**Comment by danyaljj** [comment]
You can use the TF model to predict scores (which is a bit non-trivial): https://github.com/google-research/text-to-text-transfer-transformer/blob/c10beb20c087c43af270bef4a1f19389ab8f81b4/t5/models/mtf_model.py#L238 

HF doesn't seem to have support for this yet: https://github.com/huggingface/transformers/issues/5164
