### ISSUE TITLE
Cuda Out Of Memory

### ISSUE THREAD

**Issue by NacirB** [allenai/unifiedqa#20]
Hi, 

Thank you for the great repo. 

You stated in your bart finetuning section that with one GPU (16gb), (Tesla V100 in my case) we can fit up to 64 bs. But I m still getting cuda OOM even with a bs=4.

Ps : I m finetuning your model on Ms-marco.

**Comment by shmsw25** [comment]
Hi @NacirB,

That seems unexpected. Would you check what is the minimum BS you could fit in with one 16GB GPU? And could you check the GPU memory usage (i.e. how much does it take out of 16GB) when you were able to fit the minimum BS?

**Comment by NacirB** [comment]
Hey @shmsw25 , thanks for your response. 

Here is a screen of my gpu before running the fine-tuning. 

![image](https://user-images.githubusercontent.com/36519603/113893259-22057080-97c7-11eb-8ddf-fe661e96dd66.png)

And here's a screen after fitting a bs==4 

![image](https://user-images.githubusercontent.com/36519603/113893545-6c86ed00-97c7-11eb-81c2-453095530d1d.png)

That's the maximum I can fit in this GPU.

**Comment by shmsw25** [comment]
Hi @NacirB, thanks for the screenshot. Would you share the command line you are running as well?

**Comment by NacirB** [comment]
@shmsw25  here is the command  : 

`python cli.py --do_train --output_dir out/msmarco_unifiedqa --checkpoint model/unifiedQA-uncased/best-model.pt --train_file ../data/msmarco/train.tsv  --predict_file ../data/msmarco/dev.tsv --train_batch_size 4  --predict_batch_size 4 --append_another_bos --do_lowercase --verbose --eval_period 10000`

**Comment by shmsw25** [comment]
Oh, I think I know why it causes OOM --- it's probably related to the fact that you are experimenting with MS MARCO.

The memory usage quadratically as the output length increases. Although we set the maximum output length as 100, it is usually less than 5 in the datasets we experimented with in the paper. In MS MARCO, however, the output is paragraph-level which is much longer and near to a length of 100. So essentially it is requiring much more memory.

I think you can test running the code with one of the datasets we used to test if this hypothesis is correct. If it is, I think there isn't easy way to reduce OOM for MS MARCO -- and it should be true for BART or T5 without UnifiedQA as well. Perhaps you have to use more GPUs or reduce the batch size...? Sorry that it isn't helpful.

**Comment by NacirB** [comment]
Yes I guess, I that's what's causing the issue. I think I will continue running the code with bs=4. 
Thanks for your help, I really appreciate it.
