### ISSUE TITLE
how to convert text format for multiple answers

### ISSUE THREAD

**Issue by zirui** [allenai/unifiedqa#26]
i have a  multiple choice qa-dataset  that for each question there may exist multiple corresponding answers, 
eg.
```
context: "im a  long text"
question : "xxxx"  
choices: [c1, c2, c3....cm]
answer: [c2, c4, c21]
```
the number of the answers for a question is variable,
so how should i convert the data for text-in/text-out format?
any help would be appreicated

**Comment by danyaljj** [comment]
Unfortunately, the model does not directly support this setup. But here are a couple of ways that you can do it: 

 - repeated use of multiple-choice encoding: frame it as a multiple-choice; each time that an answer is selected, exclude it from the set of the candidates and run it again. Repeat this `k` times where `k` can be an average number of correct answers. 

 - framing it as a yes/no task: for each candidate answers, modify the question and candidate answer such that it is a yes/no question for each candidate answer.

**Comment by zirui** [comment]
thanks for your reply @danyaljj , 
i will try the ways you suggested
