### ISSUE TITLE
What are "flatten", "in_metadata" and "out_metadata" in dataloader?

### ISSUE THREAD

**Issue by WindChimeRan** [allenai/unifiedqa#35]
https://github.com/allenai/unifiedqa/blob/master/bart/data.py#L76

Hi I am trying to reuse the dataloader of unifiedqa, but I have no idea what are the metadata. Can anyone explain them?

Thanks!

**Comment by danyaljj** [comment]
Meta-data was sth that we used for evaluation; so for the most part, you don't need to worry about it. 

If you'd like to run the model on your dataset or reproduce the number, I suggest you read the encoding described in the main readme.
