### ISSUE TITLE
What's new in V2?

### ISSUE THREAD

**Issue by chen-yifu** [allenai/unifiedqa#39]
Hi,
I really liked UnifiedQA T5 v1, and currently plan to use v2 for clinical QA. Do you have some high-level comments on what are the differences between v1 and v2? Thanks!

**Comment by danyaljj** [comment]
Sorry for the delay. Here is the relevant paper: https://arxiv.org/pdf/2202.12359.pdf

**Comment by chen-yifu** [comment]
Amazing, thank you!
