### ISSUE TITLE
What is the performance of BART checkpoint ? 

### ISSUE THREAD

**Issue by ratthachat** [allenai/unifiedqa#4]
Hi AI2 team,

Thanks so much for this amazing work!! 
In the paper I can see all T5 performances in the paper, Appendix A, page 11.
However, I could not find any reference on BART performance.

Could you please also illustrate BART performance on all datasets ?

Best regards,
Ratthachat

**Comment by shmsw25** [comment]
Hi @ratthachat,

We added BART experiments after posting the paper on arXiv, and are not able to update the arXiv paper at this moment. Overall, UnifiedQA with BART is comparable to T5-small or T5-large depending on datasets.

**Comment by danyaljj** [comment]
Tentatively I am including this table here: 
![Screen Shot 2020-09-21 at 5 47 49 PM](https://user-images.githubusercontent.com/2441454/93834979-92d1aa80-fc32-11ea-9a2e-3619beba8ff9.png)



The updated draft should be out in a week or two.
