### ISSUE TITLE
Reproducing Evaluation Numbers

### ISSUE THREAD

**Issue by aquaktus** [allenai/unifiedqa#43]
Hi,

I'm looking to reproduce the numbers from the Unified V1 and V2 papers.
After looking at the evaluation folder in the repo, and installing some of the publicly available dependencies like t5 from pip.
I run the command 
```
python evaluate_v2.py  --eval_path=gs://danielk-files/t5-models/union_v2_mixture_pretrained:gs:__t5-data_pretrained_models_small/small/dev_eval --target_dataset=newsqa
...
ModuleNotFoundError: No module named 'tweetqa_eval'
```

There are a few dependencies that seem necessary but I don't quite know where to find them to run evaluation on all datasets.
```
tweetqa_eval
qaconv_eval
```

Is there any tutorial for how to run this in the appropriate way to get the exact numbers form the paper?

Thanks in advance!

**Comment by danyaljj** [comment]
Added the missing files. Let me know if anything else is missing.

**Comment by aquaktus** [comment]
Thanks for the swift answer Daniel!

After running with the latest push, is `nlgeval` also somewhere? can't seem to find it on pip from tweet_eval.

**Comment by danyaljj** [comment]
https://github.com/Maluuba/nlg-eval

```
pip install git+https://github.com/Maluuba/nlg-eval.git@master
```

**Comment by aquaktus** [comment]
Looks like there's some function missing in one of the eval files `evaluate_drop_quoref_ropes`

```
$ python3 evaluate_v2.py  --eval_path=gs://danielk-files/t5-models/union_v2_mixture_pretrained:gs:__t5-data_pretrained_models_small/small/dev_eval --target_dataset=aqua_rat_test
2022-03-26 22:06:31.896407: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-26 22:06:31.896429: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "evaluate_v2.py", line 232, in <module>
    from evaluate_drop_quoref_ropes import f1_metrics as drop_quoref_ropes_f1_metrics
```

**Comment by danyaljj** [comment]
Updated it.

**Comment by aquaktus** [comment]
Now that I'm running it.
Still some issues, this time with rouge.
```
Traceback (most recent call last):
  File "evaluate_v2.py", line 237, in <module>
    from evaluate_narrativeqa import rouge_l
  File "/home/grill/Documents/carlos/unifiedqa/evaluation/evaluate_narrativeqa.py", line 9, in <module>
    rouge_l_evaluator = rouge.Rouge(
TypeError: __init__() got an unexpected keyword argument 'max_n'
```
Maybe it's a `rouge` version mismatch? I'm using rouge-1.0.1
if not, lemme know what can be done :)

**Comment by aquaktus** [comment]
Also
When I comment out the troublesome imports it starts looking for the data.
I'm using one of the commands from `evaluation_V2.py` for `aqua_rat_test` and it's asking for a particular dev file: `t2t-data/aqua_rat_test/dev.tsv`

What is the appropriate way to download the necessary data?
I'm seeing in the google bucket there isn't anything for `aqua_rat_test.tsv`, something I'm missing?
<img width="311" alt="image" src="https://user-images.githubusercontent.com/6844601/160259311-6c3d0369-f749-434a-9dac-eab82e26c12b.png">

**Comment by danyaljj** [comment]
> Maybe it's a rouge version mismatch? I'm using rouge-1.0.1 

You need this package: 
```
pip install py-rouge==1.1 
```


> I'm seeing in the google bucket there isn't anything for aqua_rat_test.tsv, something I'm missing? 

I have added the missing files there. 


<img width="306" alt="Screen Shot 2022-03-26 at 5 07 03 PM" src="https://user-images.githubusercontent.com/2441454/160261112-a4df2d67-d3db-4499-b3cd-30c6687f0be9.png">
