### ISSUE TITLE
Is there a way to get SQuAD V2 style "No Answer"?

### ISSUE THREAD

**Issue by tingofurro** [allenai/unifiedqa#45]
As stated, is it likely for the model to generate "no-ans" type text on extractive tasks, or were the unanswerable samples removed during training?

Thank you,
Philippe

**Comment by danyaljj** [comment]
Yes, "no-ans" we encoded as `<No Answer>` in the training data. See: https://github.com/allenai/unifiedqa/blob/b5439e7411b8bc8a264a9eca55c7508822cd6ae5/encode_datasets.py#L371 
In the model output, it usually appears as ` ⁇ no answer>` for whatever reason related to T5 decoder. 
The demo contains an example: 
<img width="816" alt="Screen Shot 2022-05-06 at 3 16 45 PM" src="https://user-images.githubusercontent.com/2441454/167223060-fd457d14-623a-4186-ae97-1cea30d42480.png">


Unfortunately, we never got a chance to evaluate its ability in distinguishing knowns vs unknowns.
