### ISSUE TITLE
BART weights are unavailable

### ISSUE THREAD

**Issue by tshrjn** [allenai/unifiedqa#9]
The link for the pre-trained BART weights is broken:

Link: https://nlp.cs.washington.edu/ambigqa/models/unifiedQA/unifiedQA-bart.zip

<img width="986" alt="Screen Shot 2020-11-19 at 5 39 39 PM" src="https://user-images.githubusercontent.com/8372098/99664449-31f9ff00-2a36-11eb-96d7-d2ee57eb10c9.png">

**Comment by shmsw25** [comment]
Hi, thanks for reporting! We've fixed the issue and it should be available now.
